[buffs]
# This is the option to always show out of dock power for ships when they are docked. Defaults to false
use_out_of_dock_power = false

[control]
# If you don't want any hotkeys you can set this to false
hotkeys_enabled = true

# If you prefer to disable the extended hotkeys set this to false
hotkeys_extended = true

# If you prefer to use Scopely's hotkeys set this to true
use_scopely_hotkeys = false

[graphics]
# This is an option that can be enabled to try and keep a more 'useable' UI scale size when resizing the Game Window, defaults to false
adjust_scale_res = false

# Allow borderless full screen mode, set to false to disable
borderless_fullscreen_f11 = true

# Set to 0.0 to disable a custom zoom, enter system at specified zoom otherwise, this doesn't work for the first time you view ANY system. But that should be fine
default_system_zoom = 0.0

# Allow free resizing, set to false to disable
free_resize = true

# This controls the zoom speed when using Q/E in System View, defaults to 350
keyboard_zoom_speed = 350

# To enable addtional resolution options set this to true.
show_all_resolutions = false

# This controls how quickly the the momentum falls off when letting go of the mouse, the lower the number the quicker it stops, defaults to 0.8
system_pan_momentum_falloff = 0.8

# These are used for the F1-F5 zoom hotkeys
system_zoom_preset_1 = 0.0
system_zoom_preset_2 = 0.0
system_zoom_preset_3 = 0.0
system_zoom_preset_4 = 0.0
system_zoom_preset_5 = 0.0

# These options does not appear to be used, and may be removed from future configuration
target_framerate = 60

# The amount of time to spend between transitions, increase to slow transitions down
transition_time = 0.1

# This specifies the amount to scale the UI by, 1.0 being default and anything above 1 making it larger than default, defaults to 0.9
ui_scale = 0.9

# This specifies the amount to adjust the scale by, 0.05 being default
ui_scale_adjust = 0.05

vsync = 1

# This controls the maximum zoom distance in System View, default is 2500.
# If you set this too a very high value the distance at which ship text labels are shown is also increased.
zoom = 2500


[sync]
# Token for auth on remote system
token = ''

# Url to post sync data to
url = ''

# Do you want to sync battlelogs?
battlelogs = false

# Do you want to sync building data?
buildings = false

# Do you want to sync mission data?
missions = false

# Do you want to sync owned officer data?
officer = false

# Do you want to sync research data?
research = false

# Do you want to sync inventory data?
resources = false

# Do you want to sync owned ship data?
ships = false

# Do you want to sync owned forbidden tech data?
tech = false

# Do you want to sync trait data?
traits = false


[tech]
# NOTE: The following is currently disabled in InstallWebRequestHooks() which instantly returns
#       but may be restored at some point?
#
# Set to false to leave web requests alone
fix_unity_web_requests = true

[ui]
# Skip the reveal box animation, and just open the damn boxes
always_skip_reveal_sequence = true

# Change 'false' to 'true' from the line below to remove Galaxy Chat from the game
disable_galaxy_chat = false

# Allow suppressing configured banners (disabled_banner_types) from being displayed
# This option does not appear to be used, and may be removed from future configuration
disable_toast_banners = true

# This specifies the types of Banners you DON'T want to see, This must be a comma seperated list enclosed in single quotes.
disabled_banner_types = 'Event,Victory,Defeat'

# Here is a list of POSSIBLE Banner types, I think they are relatively self explanatory.
#
# Standard
# FactionWarning
# FactionLevelUp
# FactionLevelDown
# FactionDiscovered
# IncomingAttack
# IncomingAttackFaction
# FleetBattle
# StationBattle
# StationVictory
# Victory
# Defeat
# StationDefeat
# Event
# ArmadaCreated
# ArmadaCanceled
# ArmadaIncomingAttack
# ArmadaBattleWon
# ArmadaBattleLost
# DiplomacyUpdated
# JoinedTakeover
# CompetitorJoinedTakeover
# AbandonedTerritory
# TakeoverVictory
# TakeoverDefeat

# Change 'false' to 'true' from the line below to extend the donation slider to max value for next Alliance level
extend_donation_slider = false

# Set to true to always show the rewards for selected ships/stations
show_cargo_default = false

# These should be self-explanatory
# They control the behavior of the above default option
show_player_cargo = false
show_station_cargo = true
show_hostile_cargo = true
show_armada_cargo = true

# Stay in non-restricted bundles after collecting
stay_in_bundle_after_summary = true

[shortcuts]
# Primary actions such as Mine or Attack or Go
action_primary = 'SPACE'

# Recall ship action
action_recall = 'R'
action_recall_cancel = 'SPACE'

# Repair ship action
action_repair = 'R'

# Secondary actions such as Scan
action_secondary = 'R'

# Switch between Cargo and Preview screens when clicked on a ship/node/station
action_view = 'V'

# Move the viewport down (content moves up)
move_down1 = 'DOWN'
move_down2 = 'S'

# Move the viewport left (content moves right)
move_left1 = 'LEFT'
move_left2 = 'A'

# Move the viewport right (content moves left)
move_right1 = 'RIGHT'
move_right2 = 'D'

# Move the viewport up (content moves down)
move_up1 = 'UP'
move_up2 = 'W'

# Select the Alliance tab when in chat
select_chatalliance = 'CTRL-2'

# Select the Global tab when in chat (if not disabled)
select_chatglobal = 'CTRL-1'

# Select the Private tab when in chat
select_chatprivate = 'CTRL-3'

# Select ship 1 (or locate on second press)
select_ship1 = '1'

# Select ship 2 (or locate on second press)
select_ship2 = '2'

# Select ship 3 (or locate on second press)
select_ship3 = '3'

# Select ship 4 (or locate on second press)
select_ship4 = '4'

# Select ship 5 (or locate on second press)
select_ship5 = '5'

# Select ship 6 (or locate on second press)
select_ship6 = '6'

# Select ship 7 (or locate on second press)
select_ship7 = '7'

# Select ship 8 (or locate on second press)
select_ship8 = '8'

# Go to the Away Team screen
show_awayteam = 'SHIFT-T'

# Go to the Bookmarks screen
show_bookmarks = 'B'

# Show the chat full screen
show_chat = 'C'

# Show the chat on the left side
show_chatside1 = 'ALT-C'
show_chatside2 = '`'

# Go to the Fleet Commander screen
show_commander = 'O'

# Go to the Daily Missions tab
show_daily = 'Z'

# Go to the Events screen
show_events = 'T'

# Go to the Exocomp screen
show_exocomp = 'X'

# Go to the Factions screen
show_factions = 'F'

# Go to the Galaxy view
show_galaxy = 'G'

# Go to the Inventory screen
show_inventory = 'I'

# Go to the Missions tab
show_missions = 'M'

# Go to the Officers screen
show_officers = 'SHIFT-O'

# Go to the Q Trials screen
show_qtrials = 'SHIFT-Q'

# Go to the Refinery screen
show_refinery = 'SHIFT-F'

# Go to the manage ship view
show_ships = 'N'

# Go to the Station's Exterior view
show_stationexterior = 'SHIFT-G'

# Go to the Station's Interior view
show_stationinterior = 'SHIFT-H'

# Go to the System view
show_system = 'H'

# Scale the UI down (shrink the HUD)
ui_scaledown = 'PGDOWN'

# Scale the UI up (expand the HUD)
ui_scaleup = 'PGUP'

# Adjust zoom to Presets
zoom_preset1 = 'F1'
zoom_preset2 = 'F2'
zoom_preset3 = 'F3'
zoom_preset4 = 'F4'
zoom_preset5 = 'F5'

# Set zoom presets from zoom for current session
set_zoom_preset1 = 'SHIFT-F1'
set_zoom_preset2 = 'SHIFT-F2'
set_zoom_preset3 = 'SHIFT-F3'
set_zoom_preset4 = 'SHIFT-F4'
set_zoom_preset5 = 'SHIFT-F5'

# Zoom in/out
zoom_in = 'Q'
zoom_out = 'E'
zoom_max = 'MINUS'
zoom_min = 'BACKSPACE'
zoom_reset = '='

# Toggle cargo options for current session
toggle_cargo_default = 'ALT-1'
toggle_cargo_player = 'ALT-2'
toggle_cargo_station = 'ALT-3'
toggle_cargo_hostile = 'ALT-4'
toggle_cargo_armada = 'ALT-5'

